SENHASEGURA_URL: "https://d05.poc.senhasegura.com/"
SENHASEGURA_CLIENT_ID: "4ddabf5515d5cccab85d249199f044be0646cc071"
SENHASEGURA_CLIENT_SECRET: "35e36025fb0b509d4f34d6c2b47c4194"
SENHASEGURA_MAPPING_FILE: "senhasegura-mapping.json"
