name: senhasegura CLI CI/CD

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Run DSM CLI as Running Belt
        env:
          APPLICATION: ${{ secrets.APPLICATION }}
          SYSTEM: ${{ secrets.SYSTEM }}
          ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
        run: |
      
          ./dsm runb --APLICATION "${{secrets.APPLICATION}}" --SYSTEM "${{secrets.SYSTEM}}" --ENVIRONMENT "${{secrets.ENVIRONMENT}}" --config .config.yaml --tool-name github
